services:
  db:
    container_name: viral_postgres_container
    image: postgres:17.9-alpine3.22
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  redis:
    container_name: viral_redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - my-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT__SERVICE__API_KEY=secretkey123
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  pgdata:
  redisdata: